### ISSUE TITLE
Grafana staking dashboard still has links to, and pulls info from testnet.

### ISSUE THREAD

**Issue by zimzam55** [tdslaine/install_pulse_node#11]
Grafana staking dashboard still has links to, and pulls info from testnet.  In the "validator vote summary" and "validator main info", links from the validator numbers direct to "beacon.v4.testnet.pulsechain.com".  Also the colored bar at the top has references to tPLS and shows earnings from testnet instead of mainnet.  I hope that was helpful, ty for your work :)

**Comment by zimzam55** [comment]
I know it's a not your code but maybe there is an updated version?

**Comment by tdslaine** [comment]
forked it, adjusted values and links. Added the raw-file to the monitoring script. please test, i cant
https://raw.githubusercontent.com/tdslaine/pulse-staking-dashboard/main/Yoldark_ETH_staking_dashboard.json

**Comment by zimzam55** [comment]
Tested and it looks good!  Thanks!  One thing though, all of the sections that show earnings (colored squares at the top and bar graphs at the bottom right) have numbers that are way out of whack, often showing very small gains or negative ROI, then positive then 5 minutes later negative again.  It did this on the original version too, so nothing to do with this mod.   Everything is working perfectly, no slashings and payments are arriving, just the reporting of earnings is very inaccurate.  The earnings reported on https://beacon.pulsechain.com/dashboard are also out of whack so maybe it is not a problem with the dashboard but something on pulsechain's end? idk enough to know where the dashboard pulls it's data from but thanks again, your code is killer :)
<img width="767" alt="2023-05-15_145419" src="https://github.com/tdslaine/install_pulse_node/assets/11021030/6a0be118-11c4-41d9-94ae-cfbd5bd78bb1">

**Comment by zimzam55** [comment]
oh, maybe it didn't do it in the original version.. ignore that part.. i was using one i modified using find and replace to fix the links and references to tpls ever since mainnet, not the original

**Comment by zimzam55** [comment]
found this, it probably explains it.  no action needed from you :)

```
Beacon testnet site has a bug on the summary calculations for the validators. 

Last day, last week, last month

Those seem to reset when auto withdraws are enabled. 
```

**Comment by tdslaine** [comment]
good to know, thanks for the info ^^
