### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by SvenBell** [tdslaine/install_pulse_node#15]
Hi, If one has existing validators setup already via say David Feder's scripts, How compatible would it be to start using **plsmenu**? 
Love your work

**Comment by tdslaine** [comment]
hey, thanks for the feedback. It would be super hard, nearly impossible as all of my plsmenu entries are based around my pre-setup on where things go, where they are etc. i dont think feder is even using startup-scripts for his docker run commands, so you might have to pull them together yourself. but youd also have to have the same folder structure, file permissions, ownerhsips, added groups etc..  you might backup your geth chaindata folder and migrate it to a fresh-install using my script if you wanna use plsmenu (vali-keys can be imported during setup)

**Comment by Duarab** [comment]
Do you need to enter you ip address? what happens if your ip address changes?
