### ISSUE TITLE
Ip

### ISSUE THREAD

**Issue by Duarab** [tdslaine/install_pulse_node#16]
Hi, i seen some validators you need to enter ip and update this if it changes, how does your one work?

**Comment by hexymfer** [comment]
IM not a dev myself far from it but in dip slayers script he asks for your time zone which I believe is close enough kind of  like horseshoes and hand gernades

**Comment by Duarab** [comment]
Thanks, the time shown when syncing is different from my timezone, is this time based of a main timezone all validators work from? Does dipslayer have a telegram or discord?

**Comment by tdslaine** [comment]
> Hi, i seen some validators you need to enter ip and update this if it changes, how does your one work?

hey, the ip is required in some cases for the prysm beacon - you could add the flag to you beacon/consensus config: 

--p2p-host-ip=<your public IP>: Use this if you haven't configured a DNS record for your public IP. For example: --p2p-host-ip=67.127.151.89
--p2p-host-dns="host.domain.com": For example: --p2p-host-dns=host.domain.com
 
 user first if you have a static ip, use later if you got a dyndns setup - not required, some people reported a slight improvement in connectivity (should your effecivness be good at 95-100 dont bother)

**Comment by tdslaine** [comment]
> Thanks, the time shown when syncing is different from my timezone, is this time based of a main timezone all validators work from? Does dipslayer have a telegram or discord?

yes, main utc time

**Comment by tdslaine** [comment]
see commetn above
