### ISSUE TITLE
"Backup and Restore" not opening

### ISSUE THREAD

**Issue by zimzam55** [tdslaine/install_pulse_node#17]
When selecting "Backup and Restore" the menu just jumps up to the top item "Update and Restore System" and performs no other actions.

Extra info:  It seemed to work correctly the first time I tried it, I selected "Backup and Restore" and it opened another terminal window requesting my password.  I closed the window without entering the pw.  Now each time I try, the above problem happens

**Comment by tdslaine** [comment]
1. im opening the backup & restore script via tmux - so if user connects via ssh the script continues when disconnected. 
2. your problem might be an already runnign instance of the tmux session named bandr. check with
_tmux ls_  - if its already running, connect to it with _tmux a -t bandr_
3. you can kill the tmux session with _tmux kill-session -t bandr_ (you should then be able to reopen it from plsmenu)

ill adjust the menu script, so it checks if there already is a tmux session labeld bandr running and attach to it if launched from plsmenu, if not, start a new one - that should resolve the problems.

**Comment by tdslaine** [comment]
adjusted, please run the menu updater from within plsmenu.

**Comment by zimzam55** [comment]
Thank you! I was using remote desktop not SSH fyi.  Will report back only if there is a problem :)
