### ISSUE TITLE
update and reboot system skips security updates?

### ISSUE THREAD

**Issue by zimzam55** [tdslaine/install_pulse_node#18]
Twice I ran "update and reboot system" because I had a pending security update.  After the reboot, the update is still pending.  Does it only do certain updates?

<img width="500" alt="2023-06-04_033406" src="https://github.com/tdslaine/install_pulse_node/assets/11021030/fd1cc1bd-1f56-4180-a315-bf1326167305">

**Comment by tdslaine** [comment]
hey, ill have look later - it should include kernel updates too. ill report back

**Comment by tdslaine** [comment]
added "sudo apt dist-upgrade -y" to the update routine - please check and report if it takes care of the kernel updates too (update local helper files via plsmenu)

**Comment by zimzam55** [comment]
Oh boy, trouble.  I just ran the update, (menu 1.1g) the update was successful this time.  However, I now have errors in all logs "Error response from daemon: No such container: execution", "Error response from daemon: No such container: validator", "Error response from daemon: No such container: beacon"

**Comment by tdslaine** [comment]
plsmenu > client menu > start all clients

![image](https://github.com/tdslaine/install_pulse_node/assets/46573429/f0275e09-700c-42a2-b7cf-77e255f4db43)

**Comment by zimzam55** [comment]
Worked like a charm :)
