### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Duarab** [tdslaine/install_pulse_node#21]
Just got validator activated but getting - could not request atterstation to sign at slot error=rpc error: code = unavailable desc = the node is currentyly optimistic and cannot serve validators

how do i fix this?

**Comment by tdslaine** [comment]
hey - is your local node fully synced? "the node is currentyly optimistic and cannot serve validators" usually means, you are not fully synced yet - it might take 2-3 days depending on your ISP/Speed, Peer-Connections. best to hop in onto the pulsedev tg for help: @pulsedev](https://t.me/PulseDEV)
