### ISSUE TITLE
Generating keys

### ISSUE THREAD

**Issue by reaktiiv** [tdslaine/install_pulse_node#22]
When generating keys, I am getting the following error message: 

linux-gnu
Running deposit-cli...
Traceback (most recent call last):
  File "/home/ubuntu/stakingcli/./staking_deposit/deposit.py", line 4, in <module>
    from staking_deposit.cli.existing_mnemonic import existing_mnemonic
ModuleNotFoundError: No module named 'staking_deposit'

**Comment by tdslaine** [comment]
problem seems live-boot related, missing out on pip to install requirements for the staking-cli...

updated the offline_keygen to add the universe ppa so pip can be installed. 
Please redownload the script and rerun the setup procedure

**Comment by tdslaine** [comment]
yes, fixed 
if you run it on ubuntu 22.04 LTS instead of 20.04 LTS you need to run the setup_offline_keygen.sh twice (reason unknown)
If you end up having a black-screen during that process, hit "ALT+F2".

Its adviced to run all this stuff on 20.04: https://releases.ubuntu.com/20.04.6/

**Comment by reaktiiv** [comment]
I ran it twice and it did work.
